services:
  ac-database:
    image: mysql:8.0
    restart: unless-stopped
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - ${DOCKER_DB_EXTERNAL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD:-password}
    volumes:
      - ac-database:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 10s
      retries: 40

  dbimport:
    image: dbimport
    build:
      context: .
      target: dbimport
    environment:
      AC_DATA_DIR: "/azerothcore/env/dist/data"
      AC_LOGS_DIR: "/azerothcore/env/dist/logs"
      AC_LOGIN_DATABASE_INFO: "ac-database;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_auth"
      AC_WORLD_DATABASE_INFO: "ac-database;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_world"
      AC_CHARACTER_DATABASE_INFO: "ac-database;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_characters"
      AC_CLOSE_IDLE_CONNECTIONS: "0"
    volumes:
      # The Database migration needs modules in case they have sql files
      - ${DOCKER_VOL_MODULES:-./modules}:/azerothcore/modules:ro
      - ${DOCKER_VOL_ETC:-./env/dist/etc}:/azerothcore/env/dist/etc
      # TODO(michaeldelago): disable logging to a file for docker
      - ${DOCKER_VOL_LOGS:-./env/dist/logs}:/azerothcore/env/dist/logs:delegated
    depends_on:
      ac-database:
        condition: service_healthy

  client-data-download:
    image: client-data
    build:
      context: .
      target: client-data
    volumes:
      - ${DOCKER_VOL_CLIENT_DATA:-client-data}:/azerothcore/env/dist/data

  authserver:
    image: authserver
    build:
      context: .
      target: authserver
    ports:
      - ${DOCKER_AUTH_EXTERNAL_PORT:-3724}:3724
    env_file:
        ${DOCKER_AC_ENV_FILE:-conf/dist/env.ac}
    environment:
      AC_LOGS_DIR: "/azerothcore/env/dist/logs"
      AC_TEMP_DIR: "/azerothcore/env/dist/temp"
      AC_LOGIN_DATABASE_INFO: "ac-database;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_auth"
      AC_SQLDRIVER_LOG_FILE: "SQLDriver.log"
      AC_SQLDRIVER_QUERY_LOGGING: "1"
      AC_UPDATES_ENABLE_DATABASES: "0"
    volumes:
      - ${DOCKER_VOL_ETC:-./env/dist/etc}:/azerothcore/env/dist/etc
      # TODO(michaeldelago): disable logging to a file for docker
      - ${DOCKER_VOL_LOGS:-./env/dist/logs}:/azerothcore/env/dist/logs:delegated
    depends_on:
      ac-database:
        condition: service_healthy
      dbimport:
        condition: service_completed_successfully

  worldserver:
    image: worldserver
    stdin_open: true
    tty: true
    build:
      context: .
      target: worldserver
    ports:
      - ${DOCKER_WORLD_EXTERNAL_PORT:-8085}:8085
      - ${DOCKER_SOAP_EXTERNAL_PORT:-7878}:7878
    volumes:
      - ${DOCKER_VOL_CLIENT_DATA:-client-data}:/azerothcore/env/dist/data:ro
      - ${DOCKER_VOL_ETC:-./env/dist/etc}:/azerothcore/env/dist/etc
      # TODO(michaeldelago): disable logging to a file for docker
      - ${DOCKER_VOL_LOGS:-./env/dist/logs}:/azerothcore/env/dist/logs:delegated
    env_file:
        ${DOCKER_AC_ENV_FILE:-conf/dist/env.ac}
    environment:
      AC_DATA_DIR: "/azerothcore/env/dist/data"
      AC_LOGS_DIR: "/azerothcore/env/dist/logs"
      AC_LOGIN_DATABASE_INFO: "ac-database;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_auth"
      AC_WORLD_DATABASE_INFO: "ac-database;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_world"
      AC_CHARACTER_DATABASE_INFO: "ac-database;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_characters"
      AC_CLOSE_IDLE_CONNECTIONS: "0"
      AC_UPDATES_ENABLE_DATABASES: "0"
    depends_on:
      ac-database:
        condition: service_healthy
      dbimport:
        condition: service_completed_successfully
      client-data-download:
        condition: service_completed_successfully

  # Map Extractors
  ac-tools:
    image: tools:${DOCKER_IMAGE_TAG:-master} # name of the generated image after built locally
    build:
      context: .
      target: tools
    working_dir: /azerothcore/env/client/
    volumes:
      # this is not the directory of the extracted Data
      # It's the client folder used by the extractors
      - ${DOCKER_AC_CLIENT_FOLDER:-./var/client}:/azerothcore/env/dist/bin/Data
    profiles: [tools]

volumes:
  client-data:
  ac-database:
