version: '3.9'

services:
  ac-database:
    networks:
      - ac-network
    image: mysql:8.0
    restart: unless-stopped
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - ${DOCKER_DB_EXTERNAL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_ROOT_PASSWORD:-password}
    volumes:
      - type: volume
        source: ac-database
        target: /var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 10s
      retries: 40

  # Dev server with the ./azerothcore folder binded from the host
  # Please use Linux, WSL2 or any ext-compatible filesystem
  # to avoid performance issues
  #
  ac-dev-server:
    tty: true
    image: acore/ac-wotlk-dev-server:${DOCKER_IMAGE_TAG:-master}
    user: ${DOCKER_USER:-root}
    working_dir: /azerothcore
    cap_add:
      - SYS_NICE
    build:
      context: ../
      dockerfile: "./.devcontainer/Dockerfile"
      args:
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
    security_opt:
      - seccomp:unconfined
    env_file: ${DOCKER_AC_ENV_FILE:-../conf/dist/env.ac}
    environment:
      AC_DISABLE_INTERACTIVE: "1"
    ports:
      - ${DOCKER_AUTH_EXTERNAL_PORT:-3724}:3724
      - ${DOCKER_WORLD_EXTERNAL_PORT:-8085}:8085
      - ${DOCKER_SOAP_EXTERNAL_PORT:-7878}:7878
    volumes:
      - ${DOCKER_VOL_ROOT:-../}:/azerothcore:cached
    networks:
      - ac-network
    depends_on:
      ac-database:
        condition: service_healthy

volumes:
  ac-database:

networks:
  ac-network:
