name: Sync Fork

concurrency:
  group: tag-bump
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 2' # 2PM on Tuesday

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: run sync
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh repo sync ${{ github.repository }} --source azerothcore/azerothcore-wotlk

  tag:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - id: version
        run: |
            ver="$(ls data/sql/archive/db_world -1 | sort -h | tail -n1 | cut -f1 -d '.')"
            date="$(date +%y%m%d)"

            echo "version=$ver.$date" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
